# Generated by Django 4.2.30 on 2026-04-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_flat_has_balcony'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(blank=True, null=True, verbose_name='новостройка'),
        ),
    ]
