# Generated by Django 4.2.30 on 2026-04-15 15:16

from django.db import migrations


def fill_new_building_field(apps, schema_editor):
    new_build_construction_year = 2025
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year >= 2015:
            flat.new_building = True
            flat.save()
        else:
            flat.new_building = False
            flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building_field),
    ]