# Generated by Django 4.2.30 on 2026-04-15 15:16

from django.db import migrations


def fill_new_building_field(apps, schema_editor):
    new_build_construction_year = 2015
    Flat = apps.get_model('property', 'Flat')
    
    Flat.objects.filter(construction_year__gte=new_build_construction_year)\
        .update(new_building=True)
    
    Flat.objects.filter(construction_year__lt=new_build_construction_year)\
        .update(new_building=False)

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_flat_new_building'),
    ]

    operations = [
        migrations.RunPython(fill_new_building_field),
    ]