# Generated by Django 4.2.30 on 2026-04-19 17:04

from django.db import migrations

import phonenumbers


def normalize_phone_phield(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        phone = flat.owners_phonenumber
        parse_phone = phonenumbers.parse(phone, 'RU')
        if phonenumbers.is_valid_number(parse_phone):
            flat.owner_pure_phone = parse_phone
            flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_flat_liked_by_flat_owner_pure_phone_complaint'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_phield),
    ]
