# Generated by Django 4.2.30 on 2026-04-20 07:40

from django.db import migrations

def copy_flat_owner_to_owner(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        if not flat.owner:
            continue
        owner, created = Owner.objects.get_or_create(
            owner=flat.owner,
            owners_phonenumber=flat.owners_phonenumber or '',
            owner_pure_phone=flat.owner_pure_phone or '',
        )
        owner.owners_flats.add(flat.pk)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_owner'),
    ]

    operations = [
        migrations.RunPython(copy_flat_owner_to_owner)
    ]
