# Generated by Django 4.2.30 on 2026-04-20 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_alter_owner_owner_alter_owner_owner_pure_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
    ]
