# Generated by Django 4.2.30 on 2026-04-20 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_remove_flat_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
