# Generated by Django 4.2.30 on 2026-04-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_alter_flat_liked_by_alter_owner_owners_flats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='user',
            new_name='author',
        ),
    ]
