# Generated by Django 4.2.30 on 2026-04-21 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0015_rename_user_complaint_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='кто жаловался'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='flat',
            field=models.ForeignKey(default=57329, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='property.flat', verbose_name='квартира, на которую пожаловались'),
            preserve_default=False,
        ),
    ]
