# Generated by Django 4.2.30 on 2026-04-21 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_alter_complaint_author_alter_complaint_flat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owners_flats',
            new_name='flats',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
